language: android
sudo: required
jdk:  oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-m2repository
    licenses:
      - android-sdk-license-.+
      - android-preview-license-.+
      - '.+'

before_install:
  - sudo chmod +x gradlew
  - wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
  - unzip android-ndk-r21e-linux-x86_64.zip -d $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r21e
  - export PATH=$PATH:$ANDROID_NDK_HOME

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean test

notifications:
  email: false